### ISSUE TITLE
dlt-receive can not print message in real time

### ISSUE THREAD

**Issue by voicialex** [GENIVI/dlt-daemon#263]
When using dlt to print log information, I found the message could be delay or even print out in consle with next dozens message at one time. Has anyone had the same problem?

**Comment by ssugiura** [comment]
@voicialex Could you give more detail what you are facing?

**Comment by tobohr** [comment]
I think what is meant here is that:
The time shown in dlt-receive is not time when log message was logged.
Its the time the client -> "dlt-receive" received the message  
time received in client             Timestamp
2020/11/13 15:01:53.517242 3656781397 005 ECU1 DLTD INTM log info V 1 [Test message]

**Comment by thanhbnq** [comment]
Hello all,

From my humble opinion, the original question (@voicialex ) is about dlt-receive does not really immediately print out the dlt messages coming.
I think it could be because there is a buffer for stdout. dlt-receive writes data to stdout but in order to show up, the buffer must be reached.
Could you please check by using:
**stdbuf -oL dlt-receive -a <dlt-daemon_IP>**
**Note:** "-oL" means "If MODE is 'L' the corresponding stream will be line buffered."

Hope it could help you.
Best regards,
Thanh

**Comment by voicialex** [comment]
sorry for reply so late,
Thanh has guessed my question correctly, my question is that dlt-receive doesn't print out the comming messages immediately on my console. 
In my case, I have a server to broadcast message and a client to receive these message, but sometimes, my client doesn't print out the comming log message as soon as it receive the message when I used dlt-receive.  and after a while (sometimes it could Sometimes it could take an hour ), there will print out these olddated message with the most recently message on my console together.  And also, I have change into origin printf() to print out received message, this problems did not occur!

I will try Mr Thanh 's advice and reply the result soonly

Thank you all guys

**Comment by ssugiura** [comment]
Thanks all for discussions and suggestions!
@voicialex Did you have a chance to try out?

**Comment by voicialex** [comment]
I'm not sure, because this doesn't happen 100%
But it hasn't appeared yet
