### ISSUE TITLE
A new DLT log file is created each time the device is restarted

### ISSUE THREAD

**Issue by smallert** [GENIVI/dlt-daemon#283]
Here is the content of the DLT I used to save the log profile：

cat dlt_logstorage.conf
[FILTER1]
LogAppName=DIFT,UPGD,TEST,DEMO
ContextName=.*
LogLevel=DLT_LOG_ERROR
File=Test
FileSize=10000000
NOFiles=5
SyncBehavior=ON_SPECIFIC_SIZE,ON_DEMAND
SpecificSize=2048
EcuID=ECU1

Each time the device is recharged, a new log file is generated，but if I set it to "SyncBehavior=ON_MSG" the way I set it, it wouldn't happen.
I used was version 2.18.2

**Comment by Kevin-Luong** [comment]
Hello @smallert 

Your issue is reproduced in v2.18.2 then it was fixed in DLT **v2.18.5** at the commit [logstorage: support all stragegies](https://github.com/GENIVI/dlt-daemon/commit/d49e8e3365dfc13c85506c0ff8686a708fd79f09). So could you please check your issue again with version 2.18.5?

Actually, I don't have a mass storage device or something like that to be "recharge", so I used dlt-logstorage-ctrl to connect/disconnect to the logstorage mount point. Below is my procedures to reproduce your issue:

1. Create test_logstorage/dlt_logstorage.conf with SyncBehavior=ON_SPECIFIC_SIZE,ON_DEMAND
2. dlt.conf support offline logstorage
3. In the first console, run $ dlt-daemon
4. In the second console, to connect the offline logstorage mount point, run $ dlt-logstorage-ctrl -c 1 -p test_logstorage/
5. In the third console, run $ dlt-example-user -d 10 -n 100000 TESTMESSAGE
6. Now the Test_1.dlt is created in test_logstorage/ and updated each after 2048 byte of logs
7. In the second console, to disconnect the offline logstorage mount point, run $ dlt-logstorage-ctrl -c 0 -p test_logstorage/
8. Now the Test_1.dlt is not updated anymore
9. In the second console, to re-connect the offline logstorage mount point, run $ dlt-logstorage-ctrl -c 1 -p test_logstorage/
10. Based on the DLT version, the Test_1.dlt is continually updated (v2.18.5) or the new file Test_2.dlt is created (v2.18.2)

Noted that the "SyncBehavior=ON_MSG" behavior is the same in the v2.18.2 and v2.18.5.

**Comment by smallert** [comment]
Thank you very much for your reply.
When does dlt-daemon create new log files other than when the log files reach the specified size?

**Comment by Kevin-Luong** [comment]
Hi @smallert 

From DLT v2.18.5, the offline log storage should create a new log file when it exceeds the FileSize or the newest file can not be opened. Otherwise, the newest log file should be used.

**Comment by smallert** [comment]
ok. thank you
