### ISSUE TITLE
Usage of ON Demand Sync strategy in DLT offline log storage 

### ISSUE THREAD

**Issue by Manojcv55** [GENIVI/dlt-daemon#298]
Can you please Provide the steps to use ON DEMAND Sync strategy in Offline log storage.

**Comment by Manojcv55** [comment]
Can you please Provide the steps to use  ON DEMAND Sync strategy in Offline log storage.

**Comment by thanhbnq** [comment]
Hello @Manojcv55 ,
Sorry for late response!

In order to use ON_DEMAND strategy, you should:

1. Specify relevant as our example from: https://github.com/GENIVI/dlt-daemon/blob/master/doc/dlt_offline_logstorage.md
2. Use the command "dlt-logstorage-ctrl" with following option:
    > -s[path] --snapshot=path   Sync Logstorage cache

I hope my answer is clear to you.
Best regards,
Thanh

**Comment by Manojcv55** [comment]
@thanhbnq  Thanks !! It solved my queries
